openapi: 3.0.0
info:
  title: Ticket API
  description: API for managing tickets
  version: 1.0.0
servers:
  - url: http://127.0.0.1:3000
paths:
  /tickets:
    post:
      summary: Create a new ticket
      description: This endpoint allows you to create a new ticket by providing its details.
      operationId: createTicket
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Concert Ticket"
                  description: "The name of the ticket."
                desc:
                  type: string
                  example: "A ticket for the rock concert."
                  description: "A short description of the ticket."
                allocation:
                  type: integer
                  example: 100
                  description: "The number of tickets available for this event."
              required:
                - name
                - desc
                - allocation
      responses:
        '200':
          description: Ticket created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                    description: "The unique identifier for the created ticket."
                  message:
                    type: string
                    example: "Ticket created successfully."
        '400':
          description: Invalid input data
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid input data."
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "An internal server error occurred."
  /tickets/{id}:
    get:
      summary: Retrieve a ticket by ID
      description: This endpoint retrieves the details of a specific ticket identified by its ID.
      operationId: getTicketById
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the ticket to retrieve.
          schema:
            type: integer
      responses:
        '200':
          description: Ticket retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                    description: "The unique identifier for the ticket."
                  name:
                    type: string
                    example: "Concert Ticket"
                    description: "The name of the ticket."
                  desc:
                    type: string
                    example: "A ticket for the rock concert."
                    description: "A short description of the ticket."
                  allocation:
                    type: integer
                    example: 100
                    description: "The number of tickets available for this event."
        '400':
          description: Invalid ticket ID provided
          content:
            text/plain:
              schema:
                type: string
                example: "Invalid ticket ID."
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "An internal server error occurred."
  /tickets/{id}/purchase:
    post:
      summary: Purchase a ticket
      description: This endpoint allows a user to purchase a specific ticket.
      operationId: purchaseTicket
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the ticket to purchase.
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  example: 2
                  description: "The number of tickets to purchase."
                user_id:
                  type: string
                  example: "user123"
                  description: "The ID of the user making the purchase."
              required:
                - quantity
                - user_id
      responses:
        '200':
          description: Purchase made successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Purchase completed successfully."
        '400':
          description: Bad request due to invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid quantity or user ID."